name: Scrape SET

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # repo ထဲကို commit/push လုပ်ဖို့လိုတယ်
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install puppeteer --unsafe-perm=true

      - name: Run scraper
        run: node scrape.js

      - name: Commit data.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data.json
          git commit -m "update data" || echo "no changes"
          git push
